### ISSUE TITLE
R CMD check fails with dev version of tidyr

### ISSUE THREAD

**Issue by hadley** [xfim/ggmcmc#43]
```
checking whether package ‘ggmcmc’ can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import by ‘tidyr::%>%’ when loading ‘ggmcmc’
See ‘/private/tmp/Rtmp5nYH93/check_cranb673158d7feb/ggmcmc.Rcheck/00install.out’ for details.
```
probably because you're doing too many unqualified imports

**Comment by xfim** [comment]
I'm not sure of having properly solved it. 

From what I understand, the problem was on three calls to "%>%" that were not followed by newline. I'm not sure that every call to "%>%" has to explicitly specify "tidyr::%>%" (mostly because it doesn't work). So obviously there is something that I am missing here.

If this is it, however, it must have been solved by af3980dc. Please notice that I have also messed up with git and the history does not allow to properly check the changes. Just look at R/ggs_caterpillar.R, which is the simplest one.

Can you please check if it is correct?

Thank you.

**Comment by hadley** [comment]
The root problem was probably that you were doing `@import tidyr dplyr` - both packages import and re-export `%>%` from tidyr, and this causes a problem. Does that make sense?

**Comment by xfim** [comment]
Yes, it's exactly as you describe (file /R/help.R).
Then, I guess the solution would be to import only certain functions and not both packages themselves, right?

**Comment by hadley** [comment]
Right

**Comment by xfim** [comment]
So then commit 2324e6175 should fix it.
Thank you again for your patience and willingness to help.
