### ISSUE TITLE
Choosing layout when plotting multiple parameters

### ISSUE THREAD

**Issue by lindeloev** [xfim/ggmcmc#61]
My plotting panel in Rstudio is quite small, rendering the graphs hard to read. See below. It would be very convenient to either (1) have an `ncol` argument to choose number of columns or (2) have an `faceting` argument which defaults to `TRUE` but could be set to `FALSE` so that one could do a manual `+facet_wrap(~Parameter, ncol=3)` or, say, a `+facet_grid(chain~Parameter)`. I like solution 2 better.

![image](https://user-images.githubusercontent.com/1439417/33322608-2ebcaac6-d44a-11e7-9629-d431b1376d53.png)

ggmcmc is really great! I just discovered it a week ago and I am thrilled to get MCMC into the safe home of ggplot2!

**Comment by xfim** [comment]
As explained in #56 , I prefer to give the power back to ggplot2 instead of coding all options within `ggmcmc`. Therefore, I am trying to make an effort in documenting how `ggmcmc` combines with ggplot2 back. In this sense, I have updated the documentation (3b83834). But any other example that you have in your mind will be highly appreciated.

In your specific case you could do:
`... + facet_wrap(~ Parameter, ncol = 4)`.

**Comment by lindeloev** [comment]
Thanks, that solves it and seems like the right approach. Closing.
