### ISSUE TITLE
tbl_df() is deprecated as of dplyr 1.0.0

### ISSUE THREAD

**Issue by jfiksel** [xfim/ggmcmc#70]
Running the following code:

```
library(ggmcmc)
data(radon)
s.radon.short <- radon$s.radon.short
S <- ggs(s.radon.short, family = "alpha")
```

I get a message 

```
Loading required namespace: coda
Warning message:
`tbl_df()` is deprecated as of dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
```

This indicates that there is something within the ggs function that needs to be updated to comply with dplyr 1.0.0. It would be great if you could fix this, as my packages rely on ggmcmc and CRAN does not like warnings for package submissions.

**Comment by xfim** [comment]
Thank you @jfiksel . It is already in the development version since April (see commit 2298140566ab5657883d51f15ffeb1e8e7a567aa). I only need to submit it to CRAN, but I was waiting first for dplyr-1.0 to become stable (already happened) and second to have more issues solved. But if you are planning to submit I can do it right now.

**Comment by jfiksel** [comment]
@xfim thanks so much--it's definitely not urgent, but I will probably submit sometime before August. The package has been awesome so far :)

**Comment by xfim** [comment]
Thank you very much @jfiksel, for your kind words. I appreciate it.

Then, I will have that in mind and don't delay the submission to CRAN.

**Comment by xfim** [comment]
Solved by the new ggmcmc_1.5.0
